# Config

language: cpp

notifications:
    email: false

sudo: required


# Build matrix

compiler:
    - gcc
    - clang

env:
    - CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream --with-sctp"

matrix:
    include:
        - compiler: gcc
          env: CONFOPTS=""
        - compiler: gcc
          env: CONFOPTS="--with-openssl --without-pcap --without-rtpstream"


# Build steps

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libpcap-dev libsctp-dev libncurses5-dev libssl-dev libgsl0-dev

before_script:
    - git submodule update --init
    - autoreconf -vifs
    - ./configure $CONFOPTS

script:
    - make -j2
    - make -j2 check
    - ./regress/runtests
    - ./validate-src.sh
