# Config

language: cpp
sudo: false
dist: trusty
cache: bundler
notifications:
  email: false

# Build matrix (2x compiler, 1x confopts)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libpcap-dev
      - libsctp-dev
      - libncurses5-dev
      - libssl-dev
      - libgsl0-dev

env:
  - CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream --with-sctp"

# Extend build matrix
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFOPTS="--with-openssl --without-pcap --without-rtpstream"
    - os: linux
      compiler: gcc
      env: CONFOPTS=""
    - os: linux
      compiler: gcc
      env: CONFOPTS="--disable-epoll"
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-4.6
            - libpcap-dev
            - libsctp-dev
            - libncurses5-dev
            - libssl-dev
            - libgsl0-dev
      env:
        - CC=gcc-4.6
        - CXX=g++-4.6
        - CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream --with-sctp"
    - os: osx
      compiler: clang
      env:
        - CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream"

before_script:
  - autoreconf -vifs
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi
  - ./configure $CONFOPTS

script:
  - make -j2
  - make -j2 check
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ./regress/runtests; fi
  - ./validate-src.sh
