name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: git submodule update --init
    - name: installdeps
      run: sudo apt install build-essential cmake libpcap-dev openssl libgsl-dev libsctp-dev libncurses-dev
    - name: build
      run: ./build.sh --full
  build-static:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: git submodule update --init
    - name: build-static
      run: sudo docker build -t sipp-build docker && sudo docker run -v $PWD:/src sipp-build
    - uses: actions/upload-artifact@v1.0.0
      with:
         name: sipp
         path: ./sipp
